version: '3.8'

services:
  dashboard:
    build: .
    container_name: homelab-dashboard
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - proxy-public
    depends_on:
      - glances

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    pid: "host"
    environment:
      - "GLANCES_OPT=-w"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-public
    # Port 61208 będzie dostępny w sieci, żebyś mógł sprawdzić same statystyki
    ports:
      - "61208:61208"

networks:
  proxy-public:
    external: true

