version: '3.8'

services:
  dashboard:
    build: .
    container_name: homelab-dashboard
    restart: unless-stopped
    pid: "host"
    privileged: true
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - proxy-public
    depends_on:
      - glances
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: "0:0"
    volumes:
      - /home/wojciech/security/check-security.sh:/usr/local/bin/check-security.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    pid: "host"
    privileged: true
    ports:
      - "61209:61208"
    environment:
      - "GLANCES_OPT=-w"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
      - /mnt:/mnt:ro
    networks:
      - proxy-public

networks:
  proxy-public:
    external: true

